# Generated by Django 4.2.16 on 2024-11-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("vuz", "0001_initial"),
        ("vuz", "0002_alter_main_fieldid_alter_main_progid_and_more"),
        ("vuz", "0003_alter_main_id_listedu_alter_main_id_parent"),
        ("vuz", "0004_remove_vuz_unique_idlistedu_idparent_and_more"),
        ("vuz", "0005_alter_main_course1_alter_main_course2_and_more"),
        ("vuz", "0006_remove_main_id_listedu_remove_main_id_parent_and_more"),
        ("vuz", "0007_alter_main_id_vuz"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id_district",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("district", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Districts",
            },
        ),
        migrations.CreateModel(
            name="Ministries",
            fields=[
                (
                    "id_ministry",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("ministry", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "Ministries",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("progid", models.IntegerField(primary_key=True, serialize=False)),
                ("progname", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "Program",
            },
        ),
        migrations.CreateModel(
            name="Regions",
            fields=[
                ("id_region", models.IntegerField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=40)),
                (
                    "id_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.districts"
                    ),
                ),
            ],
            options={
                "db_table": "Regions",
            },
        ),
        migrations.CreateModel(
            name="Vuz",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_listedu", models.IntegerField()),
                ("id_parent", models.IntegerField()),
                ("fullname", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=200)),
                ("rector", models.CharField(max_length=50)),
                (
                    "id_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.districts"
                    ),
                ),
                (
                    "id_ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vuz.ministries",
                    ),
                ),
                (
                    "id_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.regions"
                    ),
                ),
            ],
            options={
                "db_table": "Vuz",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "fieldid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("fieldname", models.CharField(max_length=200)),
                (
                    "progid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.program"
                    ),
                ),
            ],
            options={
                "db_table": "Training",
            },
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("profile", models.CharField(max_length=100)),
                ("formname", models.CharField(max_length=7)),
                ("course1", models.IntegerField()),
                ("course2", models.IntegerField()),
                ("course3", models.IntegerField()),
                ("course4", models.IntegerField()),
                ("course5", models.IntegerField()),
                ("course6", models.IntegerField()),
                ("course7", models.IntegerField()),
                (
                    "fieldid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.training"
                    ),
                ),
                (
                    "id_listedu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listedu_main",
                        to="vuz.vuz",
                    ),
                ),
                (
                    "id_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_main",
                        to="vuz.vuz",
                    ),
                ),
                (
                    "progid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.program"
                    ),
                ),
            ],
            options={
                "db_table": "Main",
            },
        ),
        migrations.AddConstraint(
            model_name="vuz",
            constraint=models.UniqueConstraint(
                fields=("id_listedu", "id_parent"), name="unique_idlistedu_idparent"
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="fieldid",
            field=models.ForeignKey(
                db_column="fieldid",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.training",
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="progid",
            field=models.ForeignKey(
                db_column="progid",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.program",
            ),
        ),
        migrations.AlterField(
            model_name="regions",
            name="id_district",
            field=models.ForeignKey(
                db_column="id_district",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.districts",
            ),
        ),
        migrations.AlterField(
            model_name="vuz",
            name="id_district",
            field=models.ForeignKey(
                db_column="id_district",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.districts",
            ),
        ),
        migrations.AlterField(
            model_name="vuz",
            name="id_ministry",
            field=models.ForeignKey(
                db_column="id_ministry",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.ministries",
            ),
        ),
        migrations.AlterField(
            model_name="vuz",
            name="id_region",
            field=models.ForeignKey(
                db_column="id_region",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.regions",
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="id_listedu",
            field=models.ForeignKey(
                db_column="id_listedu",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listedu_main",
                to="vuz.vuz",
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="id_parent",
            field=models.ForeignKey(
                db_column="id_parent",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_main",
                to="vuz.vuz",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="vuz",
            name="unique_idlistedu_idparent",
        ),
        migrations.AlterField(
            model_name="training",
            name="progid",
            field=models.ForeignKey(
                db_column="progid",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.program",
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="course1",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course2",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course3",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course4",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course5",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course6",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course7",
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name="main",
            name="id_listedu",
        ),
        migrations.RemoveField(
            model_name="main",
            name="id_parent",
        ),
        migrations.AlterField(
            model_name="vuz",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vuz",
            unique_together={("id_listedu", "id_parent")},
        ),
        migrations.AddField(
            model_name="main",
            name="id_vuz",
            field=models.ForeignKey(
                db_column="id_vuz",
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.vuz",
            ),
        ),
    ]
