# Generated by Django 4.2.16 on 2024-11-13 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id_district",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("district", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Districts",
            },
        ),
        migrations.CreateModel(
            name="Ministries",
            fields=[
                (
                    "id_ministry",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("ministry", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "Ministries",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("progid", models.IntegerField(primary_key=True, serialize=False)),
                ("progname", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "Program",
            },
        ),
        migrations.CreateModel(
            name="Regions",
            fields=[
                ("id_region", models.IntegerField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=40)),
                (
                    "id_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.districts"
                    ),
                ),
            ],
            options={
                "db_table": "Regions",
            },
        ),
        migrations.CreateModel(
            name="Vuz",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_listedu", models.IntegerField()),
                ("id_parent", models.IntegerField()),
                ("fullname", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=200)),
                ("rector", models.CharField(max_length=50)),
                (
                    "id_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.districts"
                    ),
                ),
                (
                    "id_ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vuz.ministries",
                    ),
                ),
                (
                    "id_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.regions"
                    ),
                ),
            ],
            options={
                "db_table": "Vuz",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "fieldid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("fieldname", models.CharField(max_length=200)),
                (
                    "progid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.program"
                    ),
                ),
            ],
            options={
                "db_table": "Training",
            },
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("profile", models.CharField(max_length=100)),
                ("formname", models.CharField(max_length=7)),
                ("course1", models.IntegerField()),
                ("course2", models.IntegerField()),
                ("course3", models.IntegerField()),
                ("course4", models.IntegerField()),
                ("course5", models.IntegerField()),
                ("course6", models.IntegerField()),
                ("course7", models.IntegerField()),
                (
                    "fieldid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.training"
                    ),
                ),
                (
                    "id_listedu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listedu_main",
                        to="vuz.vuz",
                    ),
                ),
                (
                    "id_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_main",
                        to="vuz.vuz",
                    ),
                ),
                (
                    "progid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuz.program"
                    ),
                ),
            ],
            options={
                "db_table": "Main",
            },
        ),
        migrations.AddConstraint(
            model_name="vuz",
            constraint=models.UniqueConstraint(
                fields=("id_listedu", "id_parent"), name="unique_idlistedu_idparent"
            ),
        ),
    ]
