# Generated by Django 4.2.16 on 2024-11-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vuz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main",
            name="fieldid",
            field=models.ForeignKey(
                db_column="fieldid",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.training",
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="progid",
            field=models.ForeignKey(
                db_column="progid",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.program",
            ),
        ),
        migrations.AlterField(
            model_name="regions",
            name="id_district",
            field=models.ForeignKey(
                db_column="id_district",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.districts",
            ),
        ),
        migrations.AlterField(
            model_name="vuz",
            name="id_district",
            field=models.ForeignKey(
                db_column="id_district",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.districts",
            ),
        ),
        migrations.AlterField(
            model_name="vuz",
            name="id_ministry",
            field=models.ForeignKey(
                db_column="id_ministry",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.ministries",
            ),
        ),
        migrations.AlterField(
            model_name="vuz",
            name="id_region",
            field=models.ForeignKey(
                db_column="id_region",
                on_delete=django.db.models.deletion.CASCADE,
                to="vuz.regions",
            ),
        ),
    ]
