# Generated by Django 4.2.16 on 2024-11-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vuz", "0002_alter_main_fieldid_alter_main_progid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main",
            name="id_listedu",
            field=models.ForeignKey(
                db_column="id_listedu",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listedu_main",
                to="vuz.vuz",
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="id_parent",
            field=models.ForeignKey(
                db_column="id_parent",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_main",
                to="vuz.vuz",
            ),
        ),
    ]
