# Generated by Django 4.2.16 on 2024-11-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuz", "0004_remove_vuz_unique_idlistedu_idparent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main",
            name="course1",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course2",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course3",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course4",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course5",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course6",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="course7",
            field=models.IntegerField(null=True),
        ),
    ]
