# Generated by Django 4.2.16 on 2025-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuz", "0001_initial_squashed_0007_alter_main_id_vuz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vuz",
            name="fullname",
            field=models.CharField(max_length=500),
        ),
    ]
