# Generated by Django 4.2.16 on 2025-10-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuz", "0008_alter_vuz_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main",
            name="formname",
            field=models.CharField(max_length=12),
        ),
    ]
