# Generated by Django 4.2.16 on 2026-03-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0009_alter_main_formname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_d', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dcont1', models.IntegerField(null=True)),
                ('dcont2', models.IntegerField(null=True)),
                ('dcont3', models.IntegerField(null=True)),
                ('dcont4', models.IntegerField(null=True)),
                ('dcont5', models.IntegerField(null=True)),
                ('dcont6', models.IntegerField(null=True)),
                ('dcont7', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('fielduid', models.IntegerField(primary_key=True, serialize=False)),
                ('fieldedu', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Knowledge',
            },
        ),
        migrations.AddField(
            model_name='main',
            name='dcont1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='dcont2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='dcont3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='dcont4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='dcont5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='dcont6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='dcont7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='id_d',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.CreateModel(
            name='UGNP',
            fields=[
                ('ugnp', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=80)),
                ('fielduid', models.ForeignKey(db_column='fielduid', on_delete=django.db.models.deletion.CASCADE, to='vuz.knowledge')),
            ],
            options={
                'db_table': 'UGNP',
            },
        ),
    ]
