# Generated by Django 4.2.16 on 2026-03-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0010_discount_knowledge_main_dcont1_main_dcont2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='id_d',
        ),
        migrations.RemoveField(
            model_name='main',
            name='id_d',
        ),
        migrations.AddField(
            model_name='discount',
            name='id_main',
            field=models.ForeignKey(db_column='id_main', default=0, on_delete=django.db.models.deletion.CASCADE, to='vuz.main'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
