# Generated by Django 4.2.16 on 2026-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0011_remove_discount_id_d_remove_main_id_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
