# Generated by Django 4.2.16 on 2026-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0012_alter_main_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='progcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='progcode',
            field=models.IntegerField(null=True),
        ),
    ]
