# Generated by Django 4.2.16 on 2026-03-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0013_program_progcode_training_progcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='fielduid',
            new_name='fieldeduid',
        ),
        migrations.RemoveField(
            model_name='ugnp',
            name='fielduid',
        ),
        migrations.AddField(
            model_name='ugnp',
            name='fieldeduid',
            field=models.ForeignKey(db_column='fieldeduid', default=0, on_delete=django.db.models.deletion.CASCADE, to='vuz.knowledge'),
            preserve_default=False,
        ),
    ]
